"""add phone number

Revision ID: c8d63e99a269
Revises: 5feed2721106
Create Date: 2024-09-11 11:15:43.716937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision= 'c8d63e99a269'
down_revision= '5feed2721106'
branch_labels = None
depends_on= None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
